name: Fuzzer Test

on:
  push:
    branches:
      - main

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

    - name: Build fuzzer
      run: javac Fuzzer.java

    - name: Run fuzzer
      run: |
        java Fuzzer "./html_parser_linux_x86_64"
      continue-on-error: false 

